# Assignment - 2 BUSA8090

## Student Name - Jeebak Sabu
## Student ID - 48085837

### 1. Importing Libraries and loading the CSV

In [43]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [44]:
# Reading the data (suppressing mixed‐dtype warnings)
crash_data = pd.read_csv("crash_incidents.csv", low_memory=False)

### 2. Exploring the data

In [47]:
# Display the first five rows to confirm it loaded properly
crash_data.head()

,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Hour,Crash_Nature,Crash_Type,Crash_Longitude,Crash_Latitude,...,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,Property damage only,2007,August,Wednesday,13,Angle,Multi-Vehicle,146.726025,-19.313847,...,0,0,0,2,0,0,0,0,0,0
1,2,Medical treatment,2007,December,Wednesday,8,Overturned,Single Vehicle,152.976405,-26.895647,...,1,0,1,1,0,0,0,0,0,0
2,3,Property damage only,2008,August,Wednesday,14,Overturned,Single Vehicle,152.650033,-27.884830,...,0,0,0,1,0,0,0,0,0,0
3,4,Property damage only,2007,May,Tuesday,20,Hit object,Single Vehicle,152.885188,-27.633942,...,0,0,0,1,0,0,0,0,0,0
4,5,Medical treatment,2007,July,Sunday,21,Overturned,Single Vehicle,152.838234,-27.595747,...,1,0,1,1,0,0,0,0,0,0

In [48]:
# Displaying the last five rows
crash_data.tail()

,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Hour,Crash_Nature,Crash_Type,Crash_Longitude,Crash_Latitude,...,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
393874,393875,Hospitalisation,2021,March,Monday,16,Rear-end,Multi-Vehicle,153.059431,-27.625273,...,0,0,1,2,0,0,0,0,0,0
393875,393876,Minor injury,2021,March,Tuesday,17,Rear-end,Multi-Vehicle,153.062010,-27.611300,...,0,1,1,2,0,0,0,0,0,0
393876,393877,Hospitalisation,2021,May,Thursday,8,Angle,Multi-Vehicle,153.026092,-27.411674,...,0,0,3,2,0,0,0,0,0,0
393877,393878,Medical treatment,2021,March,Sunday,10,Angle,Multi-Vehicle,153.060215,-27.621250,...,1,0,1,2,0,0,0,0,0,0
393878,393879,Medical treatment,2021,March,Wednesday,7,Rear-end,Multi-Vehicle,153.053064,-27.648228,...,1,0,1,2,0,0,0,0,0,0

In [49]:
# Show column names, non-null counts, and dtypes
crash_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 393879 entries, 0 to 393878
Data columns (total 52 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Crash_Ref_Number                 393879 non-null  int64
 1   Crash_Severity                   393879 non-null  object
 2   Crash_Year                       393879 non-null  int64
 3   Crash_Month                      393879 non-null  object
 4   Crash_Day_Of_Week                393879 non-null  object
 5   Crash_Hour                       393879 non-null  int64
 6   Crash_Nature                     393879 non-null  object
 7   Crash_Type                       393879 non-null  object
 8   Crash_Longitude                  393281 non-null  float64
 9   Crash_Latitude                   393281 non-null  float64
 10  Crash_Street                     393864 non-null  object
 11  Crash_Street_Intersecting        170932 non-null  object
 12  State_Road_Name                  181729 non-null  object
 13  Loc_Suburb                       393879 non-null  object
 14  Loc_Local_Government_Area        393879 non-null  object
 15  Loc_Post_Code                    393879 non-null  object
 16  Loc_Police_Division              393879 non-null  object
 17  Loc_Police_District              393879 non-null  object
 18  Loc_Police_Region                393879 non-null  object
 19  Loc_Queensland_Transport_Region  393879 non-null  object
 20  Loc_Main_Roads_Region            393879 non-null  object
 21  Loc_ABS_Statistical_Area_2       393879 non-null  object
 22  Loc_ABS_Statistical_Area_3       393879 non-null  object
 23  Loc_ABS_Statistical_Area_4       393879 non-null  object
 24  Loc_ABS_Remoteness               393879 non-null  object
 25  Loc_State_Electorate             393879 non-null  object
 26  Loc_Federal_Electorate           393879 non-null  object
 27  Crash_Controlling_Authority      393879 non-null  object
 28  Crash_Roadway_Feature            393879 non-null  object
 29  Crash_Traffic_Control            393879 non-null  object
 30  Crash_Speed_Limit                393876 non-null  object
 31  Crash_Road_Surface_Condition     393879 non-null  object
 32  Crash_Atmospheric_Condition      393879 non-null  object
 33  Crash_Lighting_Condition         393879 non-null  object
 34  Crash_Road_Horiz_Align           393879 non-null  object
 35  Crash_Road_Vert_Align            393878 non-null  object
 36  Crash_DCA_Code                   393879 non-null  object
 37  Crash_DCA_Description            393879 non-null  object
 38  Crash_DCA_Group_Description      393879 non-null  object
 39  DCA_Key_Approach_Dir             387311 non-null  object
 40  Count_Casualty_Fatality          393879 non-null  int64
 41  Count_Casualty_Hospitalised      393879 non-null  int64
 42  Count_Casualty_MedicallyTreated  393879 non-null  int64
 43  Count_Casualty_MinorInjury       393879 non-null  int64
 44  Count_Casualty_Total             393879 non-null  int64
 45  Count_Unit_Car                   393879 non-null  int64
 46  Count_Unit_Motorcycle_Moped      393879 non-null  int64
 47  Count_Unit_Truck                 393879 non-null  int64
 48  Count_Unit_Bus                   393879 non-null  int64
 49  Count_Unit_Bicycle               393879 non-null  int64
 50  Count_Unit_Pedestrian            393879 non-null  int64
 51  Count_Unit_Other                 393879 non-null  int64
dtypes: float64(2), int64(15), object(35)
memory usage: 156.3+ MB

In [50]:
# Descriptive statistics for numeric columns
crash_data.describe()

,Crash_Ref_Number,Crash_Year,Crash_Hour,Crash_Longitude,Crash_Latitude,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
count,393879.000000,393879.000000,393879.000000,393281.000000,393281.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000,393879.000000
mean,196940.000000,2010.396343,12.797742,151.745971,-25.827053,0.016690,0.384217,0.416559,0.221081,1.038547,1.557334,0.093722,0.076158,0.017193,0.046964,0.044757,0.024990
std,113703.217677,6.568194,5.286274,2.570115,3.232246,0.141876,0.655477,0.669954,0.514609,0.865722,0.825064,0.298746,0.280672,0.131563,0.219570,0.219239,0.158883
min,1.000000,2001.000000,0.000000,137.998204,-29.145815,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,98470.500000,2005.000000,9.000000,151.940245,-27.599155,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,196940.000000,2009.000000,13.000000,152.987656,-27.435230,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,295409.500000,2016.000000,17.000000,153.087601,-25.637447,0.000000,1.000000,1.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,393879.000000,2023.000000,23.000000,153.550268,-9.380213,5.000000,22.000000,29.000000,17.000000,32.000000,15.000000,5.000000,4.000000,3.000000,11.000000,20.000000,4.000000

### 3. Cleaning the Data

In [52]:
# Count exact‐row duplicates
dupe_count = crash_data.duplicated().sum()
print(dupe_count)

0

In [53]:
crash_data['Crash_Ref_Number'].nunique()

393879

In [54]:
# Count missing (NaN) values in each column
null_counts = crash_data.isna().sum().sort_values(ascending=False)

# Display the result
print("Missing values per column:")
print(null_counts)

Missing values per column:
Crash_Street_Intersecting          222947
State_Road_Name                    212150
DCA_Key_Approach_Dir                 6568
Crash_Longitude                       598
Crash_Latitude                        598
Crash_Street                           15
Crash_Speed_Limit                       3
Crash_Road_Vert_Align                   1
Count_Casualty_Fatality                 0
Crash_Road_Surface_Condition            0
Crash_Atmospheric_Condition             0
Crash_Lighting_Condition                0
Crash_Road_Horiz_Align                  0
Crash_DCA_Code                          0
Crash_DCA_Description                   0
Crash_DCA_Group_Description             0
Crash_Ref_Number                        0
Count_Casualty_Hospitalised             0
Count_Casualty_MedicallyTreated         0
Crash_Traffic_Control                   0
Count_Casualty_Total                    0
Count_Unit_Car                          0
Count_Unit_Motorcycle_Moped             0
Count_Unit_Truck                        0
Count_Unit_Bus                          0
Count_Unit_Bicycle                      0
Count_Unit_Pedestrian                   0
Count_Casualty_MinorInjury              0
Loc_Federal_Electorate                  0
Crash_Roadway_Feature                   0
Loc_Police_Division                     0
Crash_Year                              0
Crash_Month                             0
Crash_Day_Of_Week                       0
Crash_Hour                              0
Crash_Nature                            0
Crash_Type                              0
Loc_Suburb                              0
Loc_Local_Government_Area               0
Loc_Post_Code                           0
Loc_Police_District                     0
Crash_Controlling_Authority             0
Loc_Police_Region                       0
Loc_Queensland_Transport_Region         0
Loc_Main_Roads_Region                   0
Loc_ABS_Statistical_Area_2              0
Loc_ABS_Statistical_Area_3              0
Loc_ABS_Statistical_Area_4              0
Loc_ABS_Remoteness                      0
Loc_State_Electorate                    0
Crash_Severity                          0
Count_Unit_Other                        0
dtype: int64

In [55]:
# Filling the required catgorical columns to Unkwown for better distribution
cols_to_fill = [
    "Crash_Street_Intersecting",
    "State_Road_Name",
    "DCA_Key_Approach_Dir",
    "Crash_Street",
    "Crash_Speed_Limit",
    "Crash_Road_Vert_Align"
]

# For each column in that list, replacing NaN to "Unknown"
for col in cols_to_fill:
    if col in crash_data.columns:
        # Convert to string type first (so that "Unknown" is valid)
        crash_data[col] = crash_data[col].astype(str)
        # Wherever the value is "nan" (the string representation of NaN) or an actual NaN, set it to "Unknown"
        crash_data[col] = crash_data[col].replace("nan", np.nan).fillna("Unknown")

# Verify that those columns no longer have any missing values
print(crash_data[cols_to_fill].isna().sum())

Crash_Street_Intersecting    0
State_Road_Name              0
DCA_Key_Approach_Dir         0
Crash_Street                 0
Crash_Speed_Limit            0
Crash_Road_Vert_Align        0
dtype: int64

In [56]:
# I want to convert Crash_month to numberical(January=1, February=2,...,December=12) so that I can use it for possible analysis
# Striping whitespace and making sure everything is a string
crash_data["Crash_Month"] = crash_data["Crash_Month"].astype(str).str.strip()

# Build a month‐name to integer map 
month_map_full = {m: i for i, m in enumerate([
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
], start=1)}
month_map_abbrev = {m: i for i, m in enumerate([
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
], start=1)}

# Parsing each entry into an integer month:
def parse_month(val):
    if pd.isna(val) or val.lower() in ["", "nan", "unknown", "n/a"]:
        return np.nan
    v = val.strip()
    # If it already looks numeric then coerce
    if v.isdigit():
        num = int(v)
        return num if 1 <= num <= 12 else np.nan
    # If it matches a full month name then return that
    for name, idx in month_map_full.items():
        if v.lower() == name.lower():
            return idx
    # If it matches a three‐letter abbreviation
    for abbr, idx in month_map_abbrev.items():
        if v.lower() == abbr.lower():
            return idx
    # Otherwise cannot parse
    return np.nan

In [57]:
crash_data["Crash_Month_Int"] = crash_data["Crash_Month"].apply(parse_month).astype("Int64")

In [58]:
# 6. Verify how many months failed to parse (eg: became <NA>)
num_na_months = crash_data["Crash_Month_Int"].isna().sum()
print(f"\nRows with unparsed Crash_Month: {num_na_months} out of {len(crash_data)}")

Rows with unparsed Crash_Month: 0 out of 393879

In [59]:
# Overwriting Crash_Month with the integer version:
crash_data["Crash_Month"] = crash_data["Crash_Month_Int"]

# 8. Droping the helper column
crash_data.drop(columns=["Crash_Month_Int"], inplace=True)

In [60]:
crash_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 393879 entries, 0 to 393878
Data columns (total 52 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Crash_Ref_Number                 393879 non-null  int64
 1   Crash_Severity                   393879 non-null  object
 2   Crash_Year                       393879 non-null  int64
 3   Crash_Month                      393879 non-null  Int64
 4   Crash_Day_Of_Week                393879 non-null  object
 5   Crash_Hour                       393879 non-null  int64
 6   Crash_Nature                     393879 non-null  object
 7   Crash_Type                       393879 non-null  object
 8   Crash_Longitude                  393281 non-null  float64
 9   Crash_Latitude                   393281 non-null  float64
 10  Crash_Street                     393879 non-null  object
 11  Crash_Street_Intersecting        393879 non-null  object
 12  State_Road_Name                  393879 non-null  object
 13  Loc_Suburb                       393879 non-null  object
 14  Loc_Local_Government_Area        393879 non-null  object
 15  Loc_Post_Code                    393879 non-null  object
 16  Loc_Police_Division              393879 non-null  object
 17  Loc_Police_District              393879 non-null  object
 18  Loc_Police_Region                393879 non-null  object
 19  Loc_Queensland_Transport_Region  393879 non-null  object
 20  Loc_Main_Roads_Region            393879 non-null  object
 21  Loc_ABS_Statistical_Area_2       393879 non-null  object
 22  Loc_ABS_Statistical_Area_3       393879 non-null  object
 23  Loc_ABS_Statistical_Area_4       393879 non-null  object
 24  Loc_ABS_Remoteness               393879 non-null  object
 25  Loc_State_Electorate             393879 non-null  object
 26  Loc_Federal_Electorate           393879 non-null  object
 27  Crash_Controlling_Authority      393879 non-null  object
 28  Crash_Roadway_Feature            393879 non-null  object
 29  Crash_Traffic_Control            393879 non-null  object
 30  Crash_Speed_Limit                393879 non-null  object
 31  Crash_Road_Surface_Condition     393879 non-null  object
 32  Crash_Atmospheric_Condition      393879 non-null  object
 33  Crash_Lighting_Condition         393879 non-null  object
 34  Crash_Road_Horiz_Align           393879 non-null  object
 35  Crash_Road_Vert_Align            393879 non-null  object
 36  Crash_DCA_Code                   393879 non-null  object
 37  Crash_DCA_Description            393879 non-null  object
 38  Crash_DCA_Group_Description      393879 non-null  object
 39  DCA_Key_Approach_Dir             393879 non-null  object
 40  Count_Casualty_Fatality          393879 non-null  int64
 41  Count_Casualty_Hospitalised      393879 non-null  int64
 42  Count_Casualty_MedicallyTreated  393879 non-null  int64
 43  Count_Casualty_MinorInjury       393879 non-null  int64
 44  Count_Casualty_Total             393879 non-null  int64
 45  Count_Unit_Car                   393879 non-null  int64
 46  Count_Unit_Motorcycle_Moped      393879 non-null  int64
 47  Count_Unit_Truck                 393879 non-null  int64
 48  Count_Unit_Bus                   393879 non-null  int64
 49  Count_Unit_Bicycle               393879 non-null  int64
 50  Count_Unit_Pedestrian            393879 non-null  int64
 51  Count_Unit_Other                 393879 non-null  int64
dtypes: Int64(1), float64(2), int64(15), object(34)
memory usage: 156.6+ MB

In [27]:
# # 7.1 Export to a new CSV 
crash_data.to_csv("CrashData_clean.csv", index=False)